
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "C:/vcpkg/scripts/buildsystems/vcpkg.cmake:305 (find_program)"
      - "C:/Program Files/CMake/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:146 (include)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "Z_VCPKG_CL"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "cl"
    candidate_directories:
      - "C:/Program Files/Common Files/Oracle/Java/javapath/"
      - "C:/Program Files (x86)/VMware/VMware Workstation/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "C:/Program Files/Git/cmd/"
      - "C:/xampp/php/php.exe/"
      - "C:/Program Files/nodejs/"
      - "C:/Program Files/Curl/curl-8.12.1_4-win64-mingw/bin/curl.exe/"
      - "C:/Program Files/poppler-24.08.0/Library/bin/"
      - "C:/msys64/clang64/bin/"
      - "C:/Program Files/Java/apache-maven-3.9.11/bin/"
      - "C:/vcpkg/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Users/jacob/AppData/Local/Programs/Python/Python313/Scripts/"
      - "C:/Users/jacob/AppData/Local/Programs/Python/Python313/"
      - "C:/Users/jacob/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/jacob/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/xampp/php/"
      - "C:/Users/jacob/AppData/Local/ComposerSetup/bin/"
      - "C:/Users/jacob/AppData/Roaming/Composer/vendor/bin/"
      - "C:/Users/jacob/AppData/Roaming/npm/"
      - "C:/msys64/usr/bin/"
    searched_directories:
      - "C:/Program Files/Common Files/Oracle/Java/javapath/cl.com"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/cl.exe"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/cl"
      - "C:/Program Files (x86)/VMware/VMware Workstation/bin/cl.com"
      - "C:/Program Files (x86)/VMware/VMware Workstation/bin/cl.exe"
      - "C:/Program Files (x86)/VMware/VMware Workstation/bin/cl"
      - "C:/Windows/System32/cl.com"
      - "C:/Windows/System32/cl.exe"
      - "C:/Windows/System32/cl"
      - "C:/Windows/cl.com"
      - "C:/Windows/cl.exe"
      - "C:/Windows/cl"
      - "C:/Windows/System32/wbem/cl.com"
      - "C:/Windows/System32/wbem/cl.exe"
      - "C:/Windows/System32/wbem/cl"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/cl.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/cl.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/cl"
      - "C:/Windows/System32/OpenSSH/cl.com"
      - "C:/Windows/System32/OpenSSH/cl.exe"
      - "C:/Windows/System32/OpenSSH/cl"
      - "C:/Program Files/Docker/Docker/resources/bin/cl.com"
      - "C:/Program Files/Docker/Docker/resources/bin/cl.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/cl"
      - "C:/Program Files/Git/cmd/cl.com"
      - "C:/Program Files/Git/cmd/cl.exe"
      - "C:/Program Files/Git/cmd/cl"
      - "C:/xampp/php/php.exe/cl.com"
      - "C:/xampp/php/php.exe/cl.exe"
      - "C:/xampp/php/php.exe/cl"
      - "C:/Program Files/nodejs/cl.com"
      - "C:/Program Files/nodejs/cl.exe"
      - "C:/Program Files/nodejs/cl"
      - "C:/Program Files/Curl/curl-8.12.1_4-win64-mingw/bin/curl.exe/cl.com"
      - "C:/Program Files/Curl/curl-8.12.1_4-win64-mingw/bin/curl.exe/cl.exe"
      - "C:/Program Files/Curl/curl-8.12.1_4-win64-mingw/bin/curl.exe/cl"
      - "C:/Program Files/poppler-24.08.0/Library/bin/cl.com"
      - "C:/Program Files/poppler-24.08.0/Library/bin/cl.exe"
      - "C:/Program Files/poppler-24.08.0/Library/bin/cl"
      - "C:/msys64/clang64/bin/cl.com"
      - "C:/msys64/clang64/bin/cl.exe"
      - "C:/msys64/clang64/bin/cl"
      - "C:/Program Files/Java/apache-maven-3.9.11/bin/cl.com"
      - "C:/Program Files/Java/apache-maven-3.9.11/bin/cl.exe"
      - "C:/Program Files/Java/apache-maven-3.9.11/bin/cl"
      - "C:/vcpkg/cl.com"
      - "C:/vcpkg/cl.exe"
      - "C:/vcpkg/cl"
      - "C:/Program Files/CMake/bin/cl.com"
      - "C:/Program Files/CMake/bin/cl.exe"
      - "C:/Program Files/CMake/bin/cl"
      - "C:/Users/jacob/AppData/Local/Programs/Python/Python313/Scripts/cl.com"
      - "C:/Users/jacob/AppData/Local/Programs/Python/Python313/Scripts/cl.exe"
      - "C:/Users/jacob/AppData/Local/Programs/Python/Python313/Scripts/cl"
      - "C:/Users/jacob/AppData/Local/Programs/Python/Python313/cl.com"
      - "C:/Users/jacob/AppData/Local/Programs/Python/Python313/cl.exe"
      - "C:/Users/jacob/AppData/Local/Programs/Python/Python313/cl"
      - "C:/Users/jacob/AppData/Local/Microsoft/WindowsApps/cl.com"
      - "C:/Users/jacob/AppData/Local/Microsoft/WindowsApps/cl.exe"
      - "C:/Users/jacob/AppData/Local/Microsoft/WindowsApps/cl"
      - "C:/Users/jacob/AppData/Local/Programs/Microsoft VS Code/bin/cl.com"
      - "C:/Users/jacob/AppData/Local/Programs/Microsoft VS Code/bin/cl.exe"
      - "C:/Users/jacob/AppData/Local/Programs/Microsoft VS Code/bin/cl"
      - "C:/xampp/php/cl.com"
      - "C:/xampp/php/cl.exe"
      - "C:/xampp/php/cl"
      - "C:/Users/jacob/AppData/Local/ComposerSetup/bin/cl.com"
      - "C:/Users/jacob/AppData/Local/ComposerSetup/bin/cl.exe"
      - "C:/Users/jacob/AppData/Local/ComposerSetup/bin/cl"
      - "C:/Users/jacob/AppData/Roaming/Composer/vendor/bin/cl.com"
      - "C:/Users/jacob/AppData/Roaming/Composer/vendor/bin/cl.exe"
      - "C:/Users/jacob/AppData/Roaming/Composer/vendor/bin/cl"
      - "C:/Users/jacob/AppData/Roaming/npm/cl.com"
      - "C:/Users/jacob/AppData/Roaming/npm/cl.exe"
      - "C:/Users/jacob/AppData/Roaming/npm/cl"
      - "C:/msys64/usr/bin/cl.com"
      - "C:/msys64/usr/bin/cl.exe"
      - "C:/msys64/usr/bin/cl"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Program Files\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\Program Files (x86)\\VMware\\VMware Workstation\\bin\\"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\xampp\\php\\php.exe"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Program Files\\Curl\\curl-8.12.1_4-win64-mingw\\bin\\curl.exe"
        - "C:\\Program Files\\poppler-24.08.0\\Library\\bin"
        - "C:\\msys64\\clang64\\bin"
        - "C:\\Program Files\\Java\\apache-maven-3.9.11\\bin"
        - "C:\\vcpkg"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Users\\jacob\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\"
        - "C:\\Users\\jacob\\AppData\\Local\\Programs\\Python\\Python313\\"
        - "C:\\Users\\jacob\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\jacob\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\xampp\\php\\php.exe"
        - "C:\\xampp\\php"
        - "C:\\Users\\jacob\\AppData\\Local\\ComposerSetup\\bin"
        - "C:\\Users\\jacob\\AppData\\Roaming\\Composer\\vendor\\bin"
        - "C:\\Users\\jacob\\AppData\\Roaming\\npm"
        - "C:\\msys64\\clang64\\bin"
        - "C:\\msys64\\usr\\bin"
        - "C:\\Program Files\\Java\\apache-maven-3.9.11\\bin"
...
